INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Miso Soup', 195, 'https://hikarimiso.com/wp-content/uploads/2018/02/Basic-Miso-Soup_M1nuteMiso_HikariMiso-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'House Green Salad', 495, 'https://www.lecremedelacrumb.com/wp-content/uploads/2019/01/best-simple-green-salad-3-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Gyoza', 495, 'https://www.lafujimama.com/wp-content/uploads/2019/04/Vegan-Gyoza-2-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Edamame', 495, 'http://www.minghongfood.com/photos/large/80688%20new.gif', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Harumaki', 495, 'https://thewoksoflife.com/wp-content/uploads/2017/05/summer-rolls-10-1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Seaweed Salad', 445, 'https://i.pinimg.com/originals/d1/7b/bb/d17bbb66db93728bcfbaf113d1d1c7e0.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Agedashi Tofu', 495, 'https://www.hungryhuy.com/wp-content/uploads/1-agedashi-tofu2-1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Sunomono Salad', 395, 'https://www.oyakata.com.pl/cache/przepisy/sunomono/sunomono-salatka.jpg_alpha-0_cr-hp_500x500_im.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Chicken Karage', 495, 'http://irodoricooking.com/wp-content/uploads/2016/06/IMG_5470-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Soft Shell Crab', 795, 'https://cdn.vox-cdn.com/uploads/chorus_image/image/62089363/1-_MG_2085.0.0.jpeg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Tuna Tataki', 995, 'https://yuhoki.co.uk/image/cache/data/food/new/13_tuna%20tataki_1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Potato Croquette', 595, 'http://mymealspinner.com/uploads/recipe/coverImg/20160508_200153_s201704071622499018.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (1, 'Tuna Carppachio', 995, 'http://1.bp.blogspot.com/_EwUNOylP8Pk/TOwv5m5G8NI/AAAAAAAABTE/wA3blui-DKg/s1600/Tuna+Tartare20.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (2, 'Prawn Tempura', 745, 'https://yuhoki.co.uk/image/cache/data/food/new/4_prawn%20tempura_1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (2, 'Yam Tempura', 645, 'https://www.dashofsanity.com/wp-content/uploads/2013/10/Sweet-Potato-Foccasia-Bread-1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (2, 'Vegetable Tempura', 645, 'https://deliciouslittlebites.com/wp-content/uploads/2017/03/Wasabi-Vegetable-Tempura-9-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (2, 'Assorted Tempura', 1345, 'https://sushimonster.com.au/wp-content/uploads/2019/03/tempura-assorted.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (2, 'Appetizer Tempura', 595, 'http://japangomoncton.com/wp-content/uploads/2017/12/Assorted-Tempura.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (2, 'Sweet Potato Tempura', 645, 'https://plantbasedcityliving.com/wp-content/uploads/2018/05/Edited_April_-9-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Plain Udon', 595, 'https://www.flour.co.jp/en/images/wheatflour/SanukiNoYume-noodle.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Beef Udon', 745, 'https://i.pinimg.com/originals/a6/3e/67/a63e67ddb36f8175d9255a33f8501d46.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Chicken Udon', 745, 'https://www.mygorgeousrecipes.com/wp-content/uploads/2016/08/Miso-udon-noodle-soup-with-shiitake-mushrooms-3.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Seafood Udon', 895, 'https://www.kikusushidowntown.com/wp-content/uploads/2019/02/Udon-Nabeyaki-Udon-1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Beef Yakiudon', 995, 'https://omnivorescookbook.com/wp-content/uploads/2018/08/1808_Beef-Chow-Mein_800-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Chicken Yakiudon', 995, 'http://theblowfishgroup.com/izanagi/wp-content/uploads/2018/12/iza10019-2-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Seafood Yakiudon', 1295, 'https://www.jessicagavin.com/wp-content/uploads/2018/07/pad-thai-6-1200.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (3, 'Nabeyaki Udon', 1395, 'https://www.kikusushidowntown.com/wp-content/uploads/2019/02/Udon-Nabeyaki-Udon-1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Chicken Teriyaki', 1145, 'https://www.dinneratthezoo.com/wp-content/uploads/2018/06/slow-cooker-teriyaki-chicken-1-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Beef Teriyaki', 1145, 'https://cookingwithbliss.com/wp-content/uploads/2019/05/teriyaki-beef-stir-fry-5-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Chicken Curry', 1145, 'https://www.whiskaffair.com/wp-content/uploads/2017/12/Ginger-Chicken-Curry-4-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Beef Curry', 1145, 'https://www.swatifood.com/wp-content/uploads/2018/10/Indian-beef-curry-recipe-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Chicken Teriyaki Donburi', 1145, 'https://norecipes.com/wp-content/uploads/2012/09/easy-chicken-teriyaki-pan-fried.1024x1024-1.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Beef Teriyaki Donburi', 1145, 'https://i2.wp.com/deliciousbydesign.net/wp-content/uploads/2019/06/teriyaki-steak-2-e1559592142124.jpg?resize=500%2C500&ssl=1', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Sable Fish', 1345, 'https://www.alaskasfinestseafood.com/wp-content/uploads/2010/09/p-287-1lb_Sable_Fish___4c598d7b29182-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (4, 'Unagi Donburi', 1495, 'https://farm5.staticflickr.com/4640/38428393364_11d764fe51.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Kappa Roll', 345, 'http://japangomoncton.com/wp-content/uploads/2017/11/kappa-Roll.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Oshinko Roll', 345, 'https://greatocean.ca/wp-content/uploads/2016/11/191.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Salmon Roll', 395, 'https://sushibar-vn.com/wp-content/uploads/2016/01/NEGI-SAKE-MAKI.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Tuna Roll', 395, 'https://www.kksushi.ca/media/com_eshop/products/resized/92-650x650.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Negitoro Roll', 445, 'https://dtlscuh0h90jk.cloudfront.net/item/photos/IDGFSTI00000ngi/1541069306455535684_f3a84675415a45d49ecf9a0813bb88cd.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'California Roll', 445, 'https://norecipes.com/wp-content/uploads/2012/07/recipecalifornia-roll-recipe.1024x1024-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Salmon Avocado Roll', 495, 'https://yuhoki.co.uk/image/cache/catalog/products-images/products-20-06-2018/45.salmonavoroll-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Yam Tempura Roll', 495, 'http://christmas.365greetings.com/wp-content/uploads/2019/03/shrimp-tempura-roll-5-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'BC Roll', 495, 'https://d1marr3m5x4iac.cloudfront.net/images/edpborder500/I0-001/044/853/774-3.jpeg_/secret-food-tours-vancouver-74.jpeg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Dynamite Roll', 545, 'https://www.kksushi.ca/media/com_eshop/products/resized/SMR115-650x650.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Mango Roll', 595, 'http://japangomoncton.com/wp-content/uploads/2017/11/mango-roll.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Philadelphia Roll', 645, 'https://www.kksushi.ca/media/com_eshop/products/resized/SMR129-650x650.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Unagi Roll', 645, 'https://akirasushirestaurant.com/dynamic_content/product_images/671/533_66946604f88db47db94e266681253b40.jpeg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Chopped Scallop Roll', 495, 'https://simplyhomecooked.com/wp-content/uploads/2015/05/Shrimp-tempura-roll-2-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Spicy Salmon Roll', 495, 'https://i.pinimg.com/originals/66/7a/15/667a15f93e50a88e94ae23f43520fdd1.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (5, 'Spicy Tuna Roll', 495, 'https://i.pinimg.com/originals/84/9e/2b/849e2b0ff7626555ab0148b957ab1371.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (6, 'Tuna Cone', 445, 'https://static.thuisbezorgd.nl/images/restaurants/nl/NOO5ROQ/products/_0103_tuna-salad-handroll-nr-55.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (6, 'Salmon Cone', 445, 'http://www.wabisabi.co.mz/wp-content/uploads/2015/09/Sushi1890-retouched.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (6, 'Chopped Scallop Cone', 495, 'https://norecipes.com/wp-content/uploads/2017/07/temaki-sushi-3.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (6, 'Spicy Tuna Cone', 495, 'http://www.wabisabi.co.mz/wp-content/uploads/2017/10/T7-800x800-72dpi-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (6, 'Spicy Salmon Cone', 495, 'http://www.wabisabi.co.mz/wp-content/uploads/2015/09/T4-800x800-72dpi-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (6, 'Spicy Chopped Scallop Cone', 545, 'http://www.wabisabi.co.mz/wp-content/uploads/2015/09/Sushi1890-retouched-686x686.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Inari', 175, 'http://www.kanfood.fr/image/cache/data/produit/tag/inari-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Tamago', 175, 'https://www.mymore.com.my/image/data/ms280332/MENU/SUSHI/Sushi_15.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Hokkigai', 175, 'http://www.poppyhana.co.uk/image/cache/data/14%20(2)-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Wakame', 175, 'https://cdn.shopify.com/s/files/1/0717/1537/products/63_Chuka_Wakame_580x.jpg?v=1419392433', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Tuna', 100, 'https://i.pinimg.com/originals/f1/5b/3a/f15b3ace024ad06cb12dec03ed45baca.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Salmon', 195, 'https://stpierres.co.nz/images/20171103091534.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Sockeye Salmon', 245, 'http://www.poppyhana.co.uk/image/cache/data/3-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Masago', 245, 'https://www.eizosushi.fr/324-large_default/masago.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Saba', 195, 'https://static.thuisbezorgd.nl/images/restaurants/nl/OR0QO17/products/saba-nigiri.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Ebi', 195, 'http://chio-chio-san.az/image/cache/data/ebi-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Tobiko', 225, 'http://cdn.shopify.com/s/files/1/0717/1537/products/30_Tobikko_7fe2d8e6-9894-44a4-a3f9-e151850fe214_1024x1024.jpg?v=1419388776', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Tai', 225, 'https://daikichisushi.com/dynamic_content/product_images/71/533_00386fd2269b98b4478d81cd7e2e9b25.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Ika', 225, 'https://www.ikusushi.com/wp-content/uploads/2017/12/Ika-nigiri.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Toro', 245, 'http://getnudesushi.com/wp-content/uploads/2015/08/toro.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Tobiko & Quall Egg', 275, 'http://www.samurai.ae/wp-content/uploads/2016/10/tabiko-Sushi-A-La-Carte.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Smoked Salmon', 245, 'https://5.imimg.com/data5/IE/MD/MY-24954739/cold-smoked-salmon-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Tako', 245, 'http://www.hetpleintjedemeern.nl/image/cache/data/Nigiri_Tako-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Amaebi', 275, 'https://www.lugoshanghai.com/image/cache/data/6F6366CA-A351-402D-8A34-855040B185A7-500x500.jpeg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Hotategai', 275, 'https://linkitchen.nl/wp-content/uploads/2019/02/Nigiri-Hotategai.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Unagi', 275, 'https://www.ikusushi.com/wp-content/uploads/2017/12/Unagi-nigiri.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Ikura', 275, 'https://www.kikusushidowntown.com/wp-content/uploads/2019/02/NIGIR-lkura-1-500x500.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Hamachi', 295, 'https://www.bluesakura.nl/zwolle/image/cache/catalog/Nigiri/nigri-7-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Red Tuna', 295, 'https://www.ikusushi.com/wp-content/uploads/2017/12/tuna-nigiri.png', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (7, 'Uni', 345, 'https://i.pinimg.com/originals/ff/46/61/ff466126c400a1f7d6f75ae8917f6def.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Salmon Sashimi', 1145, 'https://yuhoki.co.uk/image/cache/data/food/sushi_sashimi/45-salmon-sashimi-93-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Tuna Sashimi', 1145, 'https://yuhoki.co.uk/image/cache/data/food/sushi_sashimi/44-tuna-sashimi-92-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Spicy Salmon Sashimi', 1245, 'https://media-cdn.tripadvisor.com/media/photo-s/08/4d/9c/3d/spicy-salmon-sashimi.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Spicy Tuna Sashimi', 1245, 'https://media-cdn.tripadvisor.com/media/photo-s/08/4d/9c/3d/spicy-salmon-sashimi.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Tuna & Salmon Sashimi', 1145, 'http://www.wabisabi.co.mz/wp-content/uploads/2015/09/S5-800x800-72dpi.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Sockeye Salmon Sashimi', 1345, 'http://www.wabisabi.co.mz/wp-content/uploads/2015/09/S3-800x800-72dpi.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Hokkigai Sashimi', 1345, 'http://labukivilnius.lt/image/cache/catalog/Products/cat83/product6696-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Toro Sashimi', 1545, 'http://novikovrestaurant.co.uk/orders/wp-content/uploads/2014/05/Chu-Toro-Portuguese-300x300.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Tako Sashimi', 1545, 'http://theblowfishgroup.com/izanagi/wp-content/uploads/2018/12/iza10170-2-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Amaebi Sashimi', 1745, 'http://labukivilnius.lt/image/cache/catalog/Products/cat83/product6703-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Hamachi Sashimi', 1745, 'http://theblowfishgroup.com/izanagi/wp-content/uploads/2018/12/iza10055-2-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Red Tuna Sashimi', 1745, 'https://yuhoki.co.uk/image/cache/data/food/sushi_sashimi/44-tuna-sashimi-92-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (8, 'Uni Sashimi', 1895, 'https://66.media.tumblr.com/c16ce93a1f494c72070a4a4ec2385a59/tumblr_p3eotkPeh51sxuwguo2_500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (9, 'Party Tray A', 2195, 'https://www.kikusushidowntown.com/wp-content/uploads/2019/03/Sushi-Combo-A-500x500.jpg', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (9, 'Party Tray B', 3595, 'https://cdn11.bigcommerce.com/s-y80oldc1cd/images/stencil/1280x1280/products/559/907/Sushi_Combo_Large__14936.1537475468.jpg?c=2&imbypass=on', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (9, 'Party Tray C', 559, 'https://cdn11.bigcommerce.com/s-y80oldc1cd/images/stencil/1280x1280/products/558/906/Sushi_Combo_Small__89865.1537474159.jpg?c=2&imbypass=on', 'true');
INSERT INTO items (category_id, name, price_cents, image, active) VALUES (9, 'Spicy Combo', 1145, 'http://littletreesushibarinc.com/wp-content/uploads/2018/09/PlatterSquare.jpg', 'true');